namespace: purestorage
name: flashblade
version: 1.19.0
readme: README.md
authors:
  - Pure Storage Ansible Team <pure-ansible-team@purestorage.com>
description: Collection of modules to manage Pure Storage FlashBlade
license:
  - GPL-3.0-or-later
  - BSD-2-Clause
tags:
  - purestorage
  - flashblade
  - storage
  - object
  - nfs
dependencies: {}
repository: https://github.com/Pure-Storage-Ansible/FlashBlade-Collection
documentation: https://docs.ansible.com/ansible/latest/collections/purestorage/flashblade/index.html#plugins-in-purestorage-flashblade
issues: https://github.com/Pure-Storage-Ansible/FlashBlade-Collection/issues
