namespace: purestorage
name: flashblade
version: 1.0.6
readme: README.md
authors:
- Pure Storage Ansible Team (@sdodsley) <pure-ansible-team@purestorage.com>
description: Collection of modules to manage Pure Storage FlashBlades
license:
 - GPL-2.0-or-later
tags:
  - purestorage
  - flashblade
  - storage
  - object
  - nfs
dependencies: {}
repository: https://github.com/Pure-Storage-Ansible/FlashBlade-Collection
documentation: https://github.com/Pure-Storage-Ansible/FlashBlade-Collection
issues: https://github.com/Pure-Storage-Ansible/FlashBlade-Collection/issues
