plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  httpapi: {}
  inventory: {}
  lookup: {}
  module:
    purefb_alert:
      description: Configure Pure Storage FlashBlade alert email settings
      name: purefb_alert
      namespace: ''
      version_added: 1.0.0
    purefb_bladename:
      description: Configure Pure Storage FlashBlade name
      name: purefb_bladename
      namespace: ''
      version_added: 1.0.0
    purefb_bucket:
      description: Manage Object Store Buckets on a  Pure Storage FlashBlade.
      name: purefb_bucket
      namespace: ''
      version_added: 1.0.0
    purefb_bucket_replica:
      description: Manage bucket replica links between Pure Storage FlashBlades
      name: purefb_bucket_replica
      namespace: ''
      version_added: 1.0.0
    purefb_connect:
      description: Manage replication connections between two FlashBlades
      name: purefb_connect
      namespace: ''
      version_added: 1.0.0
    purefb_dns:
      description: Configure Pure Storage FlashBlade DNS settings
      name: purefb_dns
      namespace: ''
      version_added: 1.0.0
    purefb_ds:
      description: Configure FlashBlade Directory Service
      name: purefb_ds
      namespace: ''
      version_added: 1.0.0
    purefb_dsrole:
      description: Configure FlashBlade  Management Directory Service Roles
      name: purefb_dsrole
      namespace: ''
      version_added: 1.0.0
    purefb_fs:
      description: Manage filesystemon Pure Storage FlashBlade`
      name: purefb_fs
      namespace: ''
      version_added: 1.0.0
    purefb_fs_replica:
      description: Manage filesystem replica links between Pure Storage FlashBlades
      name: purefb_fs_replica
      namespace: ''
      version_added: 1.0.0
    purefb_info:
      description: Collect information from Pure Storage FlashBlade
      name: purefb_info
      namespace: ''
      version_added: 1.0.0
    purefb_inventory:
      description: Collect information from Pure Storage FlashBlade
      name: purefb_inventory
      namespace: ''
      version_added: 1.0.0
    purefb_network:
      description: Manage network interfaces in a Pure Storage FlashBlade
      name: purefb_network
      namespace: ''
      version_added: 1.0.0
    purefb_ntp:
      description: Configure Pure Storage FlashBlade NTP settings
      name: purefb_ntp
      namespace: ''
      version_added: 1.0.0
    purefb_phonehome:
      description: Enable or Disable Pure Storage FlashBlade Phone Home
      name: purefb_phonehome
      namespace: ''
      version_added: 1.0.0
    purefb_policy:
      description: Manage FlashBlade policies
      name: purefb_policy
      namespace: ''
      version_added: 1.0.0
    purefb_proxy:
      description: Configure FlashBlade phonehome HTTPs proxy settings
      name: purefb_proxy
      namespace: ''
      version_added: 1.0.0
    purefb_ra:
      description: Enable or Disable Pure Storage FlashBlade Remote Assist
      name: purefb_ra
      namespace: ''
      version_added: 1.0.0
    purefb_remote_cred:
      description: Create, modify and delete FlashBlade object store remote credentials
      name: purefb_remote_cred
      namespace: ''
      version_added: 1.0.0
    purefb_s3acc:
      description: Create or delete FlashBlade Object Store accounts
      name: purefb_s3acc
      namespace: ''
      version_added: 1.0.0
    purefb_s3user:
      description: Create or delete FlashBlade Object Store account users
      name: purefb_s3user
      namespace: ''
      version_added: 1.0.0
    purefb_smtp:
      description: Configure SMTP for Pure Storage FlashBlade
      name: purefb_smtp
      namespace: ''
      version_added: 1.0.0
    purefb_snap:
      description: Manage filesystem snapshots on Pure Storage FlashBlades
      name: purefb_snap
      namespace: ''
      version_added: 1.0.0
    purefb_snmp_agent:
      description: Configure the FlashBlade SNMP Agent
      name: purefb_snmp_agent
      namespace: ''
      version_added: 1.0.0
    purefb_snmp_mgr:
      description: Configure FlashBlade SNMP Managers
      name: purefb_snmp_mgr
      namespace: ''
      version_added: 1.0.0
    purefb_subnet:
      description: Manage network subnets in a Pure Storage FlashBlade
      name: purefb_subnet
      namespace: ''
      version_added: 1.0.0
    purefb_target:
      description: Manage remote S3-capable targets for a FlashBlade
      name: purefb_target
      namespace: ''
      version_added: 1.0.0
    purefb_user:
      description: Modify FlashBlade local user account password
      name: purefb_user
      namespace: ''
      version_added: 1.0.0
  netconf: {}
  shell: {}
  strategy: {}
  vars: {}
version: 1.3.0
