name: Pure Storage Ansible CI

on:
  pull_request:
  # Run CI once per day (at 06:00 UTC)
  # This ensures that even if there haven't been commits that we are still testing against latest version of ansible-test and ansible-core
  schedule:
    - cron: '0 6 * * *'
    
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install purity_fb pycodestyle flake8 pytz
        pip install git+https://github.com/ansible/ansible.git@devel
        # pip install ansible-core
    - name: Run pycodestyle
      run: |
        pycodestyle --max-line-length=160 --ignore=E305,E402,W503,W504,E722,E741,W606 ./
    - name: Run sanity tests
      run: |
        cd collections/ansible_collections/purestorage/flashblade
        ansible-test sanity --docker -v --color
    - name: Run flake8
      run: |
        flake8 . --exit-zero --isolated --ignore E402 --select E,F,W --max-line-length 160
