name: Pure Storage Ansible CI

on:
  pull_request:
  push:
  schedule:
    - cron: '25 10 * * *'

jobs:
  build:
    name: Build flashblade on Ansible ${{ matrix.ansible }} (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ansible:
          - stable-2.11
          - stable-2.12
          - stable-2.13
        python-version:
          - 3.8
          - 3.9
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python${{ matrix.python }} -m pip install --upgrade pip
        python${{ matrix.python }} -m pip install https://github.com/ansible/ansible/archive/${{ matrix.ansible }}.tar.gz --disable-pip-version-check

    - name: Run sanity tests
      run: |
        pwd
        mkdir -p ansible_collections/purestorage/flashblade
        rsync -av . ansible_collections/purestorage/flashblade --exclude ansible_collection/purestorage/flashblade
        cd ansible_collections/purestorage/flashblade
        ansible-test sanity -v --color --python ${{ matrix.python-version }} --docker
